execute-dir: file
project:
  type: website
  output-dir: docs

website:
  title: "Advent of Code"
  navbar:
    left:
      - href: index.qmd
        text: "Tilbage til forsiden"

format:
  html:
    theme: cosmo
    toc: false
    page-layout: full